"""add_device_id_to_fridges

Revision ID: 3fcb0e7e63b3
Revises: 1a0551aaf2b4
Create Date: 2025-12-09 04:35:14.578690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcb0e7e63b3'
down_revision: Union[str, Sequence[str], None] = '1a0551aaf2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridges', sa.Column('device_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_fridges_device_id'), 'fridges', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridges_device_id'), table_name='fridges')
    op.drop_column('fridges', 'device_id')
    # ### end Alembic commands ###
