"""added name for shopping list

Revision ID: 438e524fb31e
Revises: ab70983a567e
Create Date: 2025-12-03 05:45:05.438305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438e524fb31e'
down_revision: Union[str, Sequence[str], None] = 'ab70983a567e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_lists', 'name')
    # ### end Alembic commands ###
