"""Add recipe_id to shopping_lists

Revision ID: 5948aa1dce59
Revises: 438e524fb31e
Create Date: 2025-12-03 06:28:39.599405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5948aa1dce59'
down_revision: Union[str, Sequence[str], None] = '438e524fb31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
