"""Better relation between recipes suggestion and shopping list

Revision ID: 79ba65ac8eb7
Revises: a48fef119846
Create Date: 2025-12-02 16:56:46.621228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ba65ac8eb7'
down_revision: Union[str, Sequence[str], None] = 'a48fef119846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
