"""Removed Device component and consolidate into Fridge

Revision ID: 7ce80a32227a
Revises: ff304db19f42
Create Date: 2025-11-30 04:29:09.372321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce80a32227a'
down_revision: Union[str, Sequence[str], None] = 'ff304db19f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridge_devices_device_id'), table_name='fridge_devices')
    op.drop_index(op.f('ix_fridge_devices_id'), table_name='fridge_devices')
    op.drop_index(op.f('ix_fridge_devices_pairing_code'), table_name='fridge_devices')
    op.drop_table('fridge_devices')
    op.add_column('fridges', sa.Column('kiosk_id', sa.String(), nullable=False))
    op.add_column('fridges', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('fridges', sa.Column('pairing_code', sa.String(), nullable=True))
    op.add_column('fridges', sa.Column('is_paired', sa.Boolean(), nullable=True))
    op.add_column('fridges', sa.Column('paired_at', sa.DateTime(), nullable=True))
    op.add_column('fridges', sa.Column('last_heartbeat', sa.DateTime(), nullable=True))
    op.add_column('fridges', sa.Column('kiosk_metadata', sa.JSON(), nullable=True))
    op.alter_column('fridges', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_fridges_kiosk_id'), 'fridges', ['kiosk_id'], unique=True)
    op.create_index(op.f('ix_fridges_pairing_code'), 'fridges', ['pairing_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fridges_pairing_code'), table_name='fridges')
    op.drop_index(op.f('ix_fridges_kiosk_id'), table_name='fridges')
    op.alter_column('fridges', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('fridges', 'kiosk_metadata')
    op.drop_column('fridges', 'last_heartbeat')
    op.drop_column('fridges', 'paired_at')
    op.drop_column('fridges', 'is_paired')
    op.drop_column('fridges', 'pairing_code')
    op.drop_column('fridges', 'device_name')
    op.drop_column('fridges', 'kiosk_id')
    op.create_table('fridge_devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fridge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pairing_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_paired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fridge_id'], ['fridges.id'], name=op.f('fridge_devices_fridge_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fridge_devices_pkey'))
    )
    op.create_index(op.f('ix_fridge_devices_pairing_code'), 'fridge_devices', ['pairing_code'], unique=True)
    op.create_index(op.f('ix_fridge_devices_id'), 'fridge_devices', ['id'], unique=False)
    op.create_index(op.f('ix_fridge_devices_device_id'), 'fridge_devices', ['device_id'], unique=True)
    # ### end Alembic commands ###
