"""Rely recipes and shopping list

Revision ID: a48fef119846
Revises: 7ce80a32227a
Create Date: 2025-12-02 15:38:45.914874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48fef119846'
down_revision: Union[str, Sequence[str], None] = '7ce80a32227a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.add_column('shopping_lists', sa.Column('status', sa.String(), nullable=True))
    op.add_column('shopping_lists', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'shopping_lists', 'recipes', ['recipe_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.drop_column('shopping_lists', 'completed_at')
    op.drop_column('shopping_lists', 'status')
    op.drop_column('shopping_lists', 'recipe_id')
    # ### end Alembic commands ###
