"""Better relation between recipes suggestion and shopping list

Revision ID: ab70983a567e
Revises: 79ba65ac8eb7
Create Date: 2025-12-02 17:08:25.423170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab70983a567e'
down_revision: Union[str, Sequence[str], None] = '79ba65ac8eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
