"""Add fridge_id to recipes favorites

Revision ID: be92f52d4026
Revises: 3fcb0e7e63b3
Create Date: 2025-12-11 04:07:24.086772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be92f52d4026'
down_revision: Union[str, Sequence[str], None] = '3fcb0e7e63b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_favorites', sa.Column('fridge_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipe_favorites_fridge_id'), 'recipe_favorites', ['fridge_id'], unique=False)
    op.create_foreign_key(None, 'recipe_favorites', 'fridges', ['fridge_id'], ['id'], ondelete='CASCADE')
    op.add_column('recipes', sa.Column('fridge_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recipes_fridge_id'), 'recipes', ['fridge_id'], unique=False)
    op.create_foreign_key(None, 'recipes', 'fridges', ['fridge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_index(op.f('ix_recipes_fridge_id'), table_name='recipes')
    op.drop_column('recipes', 'fridge_id')
    op.drop_constraint(None, 'recipe_favorites', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_favorites_fridge_id'), table_name='recipe_favorites')
    op.drop_column('recipe_favorites', 'fridge_id')
    # ### end Alembic commands ###
