"""Add performance indexes

Revision ID: ff304db19f42
Revises: ff96cfc6f917
Create Date: 2025-11-28 01:37:16.830902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff304db19f42'
down_revision: Union[str, Sequence[str], None] = 'ff96cfc6f917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_alert_created_status', 'alerts', ['created_at', 'status'], unique=False)
    op.create_index('ix_alert_fridge_status', 'alerts', ['fridge_id', 'status'], unique=False)
    op.create_index('ix_alert_fridge_type_status', 'alerts', ['fridge_id', 'type', 'status'], unique=False)
    op.create_index('ix_event_fridge_created', 'events', ['fridge_id', 'created_at'], unique=False)
    op.create_index('ix_event_fridge_type', 'events', ['fridge_id', 'type'], unique=False)
    op.create_index('ix_event_item_created', 'events', ['inventory_item_id', 'created_at'], unique=False)
    op.add_column('fridge_devices', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.create_index('ix_inventory_expiry_quantity', 'inventory_items', ['expiry_date', 'quantity'], unique=False)
    op.create_index('ix_inventory_fridge_expiry', 'inventory_items', ['fridge_id', 'expiry_date'], unique=False)
    op.create_index('ix_inventory_fridge_lastseen', 'inventory_items', ['fridge_id', 'last_seen_at'], unique=False)
    op.create_index('ix_inventory_fridge_quantity', 'inventory_items', ['fridge_id', 'quantity'], unique=False)
    op.create_index(op.f('ix_inventory_items_last_seen_at'), 'inventory_items', ['last_seen_at'], unique=False)
    op.add_column('products', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_column('products', 'extra_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('products', 'extra_data')
    op.drop_index(op.f('ix_inventory_items_last_seen_at'), table_name='inventory_items')
    op.drop_index('ix_inventory_fridge_quantity', table_name='inventory_items')
    op.drop_index('ix_inventory_fridge_lastseen', table_name='inventory_items')
    op.drop_index('ix_inventory_fridge_expiry', table_name='inventory_items')
    op.drop_index('ix_inventory_expiry_quantity', table_name='inventory_items')
    op.drop_column('fridge_devices', 'extra_data')
    op.drop_index('ix_event_item_created', table_name='events')
    op.drop_index('ix_event_fridge_type', table_name='events')
    op.drop_index('ix_event_fridge_created', table_name='events')
    op.drop_index('ix_alert_fridge_type_status', table_name='alerts')
    op.drop_index('ix_alert_fridge_status', table_name='alerts')
    op.drop_index('ix_alert_created_status', table_name='alerts')
    # ### end Alembic commands ###
